server:
  port: 9001


spring:
  mvc:
    view:
      # 定位模板的目录
      prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
#=================================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootdo
    username: root
    password: 123456

# ================================================
#                   Thymeleaf配置
# ================================================
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    check-template-location: true

# ================================================
#                   Mybatis配置
# ================================================
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.fbj.blog.entity

